apiVersion: eks.amazonaws.com/v1
kind: IngressClassParams
metadata:
  name: alb
  namespace: n8n
spec:
  scheme: internet-facing
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: alb
  namespace: n8n
  labels:
    project: n8n-demo
spec:
  controller: eks.amazonaws.com/alb
  parameters:
    apiGroup: eks.amazonaws.com
    kind: IngressClassParams
    name: alb