# Values that will be set by Terraform
valkey:
  clusterNodes: ""

cloudfront:
  domainName: ""
  customHeaderValue: ""

database:
  secretName: ""

encryption:
  secretName: ""

serviceAccount:
  roleArn: ""
  
ingress:
  enabled: true
  className: "alb"
  annotations:
    # --- ADD THIS LINE ---
    alb.ingress.kubernetes.io/scheme: internet-facing
    # ---------------------
    # (Keep other existing annotations like target-type or listen-ports)

# Values that can be manually set
main:
  image:
    repository: n8nio/n8n
    tag: latest
  resources:
    requests:
      memory: "1G"
    limits:
      memory: "2G"

worker:
  replicas: 1
  resources:
    requests:
      memory: "1G"
    limits:
      memory: "2G"

webhook:
  replicas: 1
  resources:
    requests:
      memory: "1G"
    limits:
      memory: "2G"
